//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geri_Sayimlar", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Geri_Sayimlar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TarihField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGeriSayimService")]
    public interface IGeriSayimService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeriSayimService/DoWork", ReplyAction="http://tempuri.org/IGeriSayimService/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeriSayimService/DoWork", ReplyAction="http://tempuri.org/IGeriSayimService/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeriSayimService/GetAllXML", ReplyAction="http://tempuri.org/IGeriSayimService/GetAllXMLResponse")]
        WCF_Client.ServiceReference1.Geri_Sayimlar[] GetAllXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeriSayimService/GetAllXML", ReplyAction="http://tempuri.org/IGeriSayimService/GetAllXMLResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Geri_Sayimlar[]> GetAllXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeriSayimService/GetAllJSON", ReplyAction="http://tempuri.org/IGeriSayimService/GetAllJSONResponse")]
        string GetAllJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeriSayimService/GetAllJSON", ReplyAction="http://tempuri.org/IGeriSayimService/GetAllJSONResponse")]
        System.Threading.Tasks.Task<string> GetAllJSONAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeriSayimServiceChannel : WCF_Client.ServiceReference1.IGeriSayimService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeriSayimServiceClient : System.ServiceModel.ClientBase<WCF_Client.ServiceReference1.IGeriSayimService>, WCF_Client.ServiceReference1.IGeriSayimService {
        
        public GeriSayimServiceClient() {
        }
        
        public GeriSayimServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeriSayimServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeriSayimServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeriSayimServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public WCF_Client.ServiceReference1.Geri_Sayimlar[] GetAllXML() {
            return base.Channel.GetAllXML();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Geri_Sayimlar[]> GetAllXMLAsync() {
            return base.Channel.GetAllXMLAsync();
        }
        
        public string GetAllJSON() {
            return base.Channel.GetAllJSON();
        }
        
        public System.Threading.Tasks.Task<string> GetAllJSONAsync() {
            return base.Channel.GetAllJSONAsync();
        }
    }
}
