//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Client.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IGeriSayimSecureService")]
    public interface IGeriSayimSecureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeriSayimSecureService/TestSifre", ReplyAction="http://tempuri.org/IGeriSayimSecureService/TestSifreResponse")]
        string TestSifre();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeriSayimSecureService/TestSifre", ReplyAction="http://tempuri.org/IGeriSayimSecureService/TestSifreResponse")]
        System.Threading.Tasks.Task<string> TestSifreAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeriSayimSecureServiceChannel : WCF_Client.ServiceReference2.IGeriSayimSecureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeriSayimSecureServiceClient : System.ServiceModel.ClientBase<WCF_Client.ServiceReference2.IGeriSayimSecureService>, WCF_Client.ServiceReference2.IGeriSayimSecureService {
        
        public GeriSayimSecureServiceClient() {
        }
        
        public GeriSayimSecureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeriSayimSecureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeriSayimSecureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeriSayimSecureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestSifre() {
            return base.Channel.TestSifre();
        }
        
        public System.Threading.Tasks.Task<string> TestSifreAsync() {
            return base.Channel.TestSifreAsync();
        }
    }
}
